language: node_js
node_js:
  - "6.2"
before_install:
  npm install -g grunt-cli
env:
  - TEST_POUCHDB=true
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
